USE [master]
GO

/****** Object:  Database [ElectronicStore]    Script Date: 25.03.2026 14:47:25 ******/
CREATE DATABASE [ElectronicStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ElectronicStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ElectronicStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ElectronicStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ElectronicStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ElectronicStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ElectronicStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ElectronicStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ElectronicStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ElectronicStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ElectronicStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [ElectronicStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ElectronicStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ElectronicStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ElectronicStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ElectronicStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ElectronicStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ElectronicStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ElectronicStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ElectronicStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ElectronicStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ElectronicStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ElectronicStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ElectronicStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ElectronicStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ElectronicStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ElectronicStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ElectronicStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ElectronicStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ElectronicStore] SET  MULTI_USER 
GO

ALTER DATABASE [ElectronicStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ElectronicStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ElectronicStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ElectronicStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ElectronicStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ElectronicStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ElectronicStore] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ElectronicStore] SET  READ_WRITE 
GO

